== Repo README Template

This template is used to create ReadMe documentation. The Examples
section is for use if the repository will be used by consuming
developers. Going forward, contributing developers will find their
documentation in the Contributing.md.

[width="98%",cols="<15%,66%,15%,4%",options="header",]
|===
|*Reviews and Approvals* | | |
|*Purpose* |Template for Creating ReadMe documentation. | |

|*Jira* |NA | |

|*Author*
|https://carrier-digital.atlassian.net/wiki/people/61eb8a245fcc3700689d3b4e?ref=confluence[Creadick&#44;
Peyton] | |

|*Reviewer*
|https://carrier-digital.atlassian.net/wiki/people/6114ea2c75ad960069a761d4?ref=confluence[Nikita
Slupko]
https://carrier-digital.atlassian.net/wiki/people/608299309c4625006b4a8fd6?ref=confluence[Tatiana
Mikhalenok]
https://carrier-digital.atlassian.net/wiki/people/6374eab6489de2f7f461f592?ref=confluence[Syrtsov&#44;
Alexander (Contractor) (Deactivated)] | |

|*Document Status / Date / Rev #* |APPROVED |30 de jan. de 2023 |2.0

|*Date Last Reviewed* |1 de fev. de 2023 | |
|===

Elements of this ReadMe (codeblocks and the TOC) don’t render fully
using the *Confluence* Markdown Macro. They will render correctly in the
repository.

To use this ReadMe as a template:

[arabic]
. Edit this page,
. edit the macro,
. Copy the Markdown.

== Name of What is in repo

{empty}[TOC]

Delete All Template Guidance or blocks of template guidance, including
this sentence, from your document. *Use absolute links or they will
break in Code Artifactory.*

=== Overview

Template Guidance:

- Work with TW on Overview. Do not wait until the end of the sprint.

- This overview should be in both the Confluence and Repo doc when high
level Confluence doc exists. The Repo should include a briefer version
of the Confluence overview along with what is in the repo, and what the
documentation is intended to do.

==== Repository Documentation

[width="97%",cols="<23%,<77%",options="header",]
|===
|*Markdown Link* |*Description*
|Contributing Guide |Contains the documentation for developers making
changes in the repository.

|Docs ReadMe |Contains TypeDoc Generated Markdown for Classes, Enums,
etc
|===

Template Guidance:

In the above table:

- Links to the docs folder if the repo uses TypeDocs to generate
documentation for classes / enums / etc.

- Link to the Contributing guide.

==== Relevant Confluence Documentation

[width="98%",cols="<62%,<38%",options="header",]
|===
|*Confluence Page* |*Description*
|Page Title |Description

|https://carrier-digital.atlassian.net/wiki/spaces/IO/pages/2108063771[Carrier.io
Glossary] |Confluence Glossary for Carrier.io Terms and Definitions
|===

Template Guidance for Confluence Documentation Links:

- List and Link to high level overview and architecture page in
Confluence.

- Do not link to epic-specific architecture. It is a static page that
will be merged into the main architecture for the service, domain, or
other components.

- Include Glossary **AT THE BOTTOM**.

- Remove the page name from the Confluence link. Confluence locates
pages by the key (sequence of numbers in the url right before the page
name).

=== Architecture

https://carrier-digital.atlassian.netlink[Solution Architecture on
Confluence]

Architecture guidance: don't link to the static epic architecture. This
link should go to the living architecture for the solution, component,
etc.

=== Instructions

Any instructions needed by both contributing and consuming developers
will be located in the Reference folder and linked from this section.

Template Guidance for instructions:

This section is optional and should be removed if not needed. It is for
instructions needed by contributing developers to use what is in the
repo.

If there are instructions that are identical for both consuming and
contributing developers:

- Create a Reference folder in the Repo

- Create separate markdown files for each instruction.

- Include the guidance above that instructions needed by both
contributing and consuming developers are located in the Reference
folder. Link to them from the ReadMe and Contributing Guide.

==== Instruction Heading

=== Examples

Template Guidance for Examples:

Examples can be code examples or relevant information for consuming
developers. Examples should be meaningful. If this repository requires
more comprehensive instructions (not common), add an Instructions
section.

Insert code in code block. Use syntax highlighting when possible.
